### PR TITLE
ToolbarController changes

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Replaced stock toolbar code with the ToolbarController

    Note that the .csproj file was NOT modified, I provided a slightly
    modified version in ProgressiveColonizationSystem.csproj-modified

    This will require adding the ToolbarController as a reference to build,
    and in games, will require both the ToolbarController and
    ClickThroughBlocker (used by ToolbarController) to be installed.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Steve, I accidentally committed a changed copy of the csproj, and don't have time to redo this.  If you need me to fix it, let me know and I'll try to get to it tomorrow, otherwise just save your copy of the csproj file when merging and restore it manually

**Comment by SteveBenz** [comment]
Okay, so you can see from the trail of commits that I've found some time to look at it and, well, had some thoughts...

My vision for the PksToolbarDialog was that it was a self-contained thing that anybody could just drop into their mod.  It'd work for that, plus or minus the problems with multiple mods dealing with toolbars that ToolbarController addresses.

ToolbarController has an entirely different vision when it comes to the toolbar - it figures that every mod will be able to declare up front what buttons it deploys, and that's a reasonable thing to assume...  It just flies in the face of what I wanted when I created PksToolbarDialog.  That's why your implementation ended up with so much duplicate code, inconsistent method permissions and classes with unclear purposes.  It needed a redesign, which is not a thing I can expect of an outside contributor.

It took me a while to reconcile it all.  My feeling is that ToolbarController's view of the world should prevail.  (Various reasons).  So I completed the divorce between my dialog base class and the toolbar.  You had put a bunch of code to draw the toolbar button differently when it was selected vs. not, which wasn't there in the original mod and none of the mods I normally use have that behavior, so cutting that made the divorce a whole lot simpler.

Alas, I'm sad that you didn't notice or avail yourself of the scheme I put in place for being able to customize the .csproj without having to edit the .csproj itself!  When I first started modding, I saw lots of mods with all sorts of nasty hard-coded paths in the .csproj file that would lead to a constant spew of chaff in the .csproj's history if multiple devs worked on it.  So I applied some msbuild mojo to it to make that not true in my mod.  (I'm talking about the ksplocations.props file)

If you didn't see it, I wonder if you just dove right into the .csproj file without trying to compile it first because you've done this sort of hackery a million times already and just did the same thing you always do?  Maybe a fat comment in the .csproj file would have helped?

I'm going to go ahead and merge this now, as it seems to work.  But it does have one small squawk - the tooltip doesn't show up.  Not sure why that would be.

I'm going to be offline for about a week (decompressing from work crazy).  I hope to put out a release around the 14th that'll include this.

Please double-check my .netkan file - I'm pretty sure I want to depend on ToolbarControl and not Toolbar.  I also added a dependency on ClickThroughBlocker, but that's as-yet aspirational.  I've been meaning to add support for that for some time now.

**Comment by linuxgurugamer** [comment]
Regarding "Alas, I'm sad that you didn't notice or avail yourself of the scheme I put in place for being able to customize the .csproj without having to edit the .csproj itself! When I first started modding, I saw lots of mods with all sorts of nasty hard-coded paths in the .csproj file that would lead to a constant spew of chaff in the .csproj's history if multiple devs worked on it. So I applied some msbuild mojo to it to make that not true in my mod. (I'm talking about the ksplocations.props file)"

It's a good implementation, but I have 200+ mods doing it a different way.  If it was a one-off, then I'd consider it, but I'm not going to change 200 mods for results which I already have in a different way.

I did see it, but just cut it out and adapted it to my normal build process.   I wasn't aware that I could put comments into the csproj file, so I just learned something.

So yes, I essentially made changes to the csproj to confirm with my methods.  I didn't mean to send it up to you, it escaped (just like Jeb)

I'll pull your changes and then add the ButtonManager code.  It's actually pretty simple, just changing about 6-8 lines.  The ButtonManager is already out in my SpaceTuxLibrary, and I'm in the process of releasing those mods of mine which need it.

Netkan, yes, dependency on ToolbarControl AND ClickThroughBlocker (needed by toolbarControl).

The ClickThroughBlocker is even easier, it's just replacing GUILayout.Window with ClickThruBlocker.GUILayoutWindow (and the same for GUI.Window).  If you like, I can do that at the same time as the ButtonManager, let me know.

I'll look to see why the tooltip isn't showing up.

**Comment by SteveBenz** [comment]
I had a look at ClickThruBlocker today and I don't think I need it.  PKS is using the newer Unity(?) functions for creating dialogs (DialogGUIBase and friends).  Best I can figure that gives me the effect we need by default.  I tested it by moving the PKS dialog over various other dialogs.  If I drag it over a KSP thing - e.g. a tweakables dialog for a part, then my dialog is rendered on top of it and clicks on my dialog only go to my controls and not the tweakable behind it.  If I drag it over Kerbal Engineer or Kerbal Alarm Clock dialogs, then my dialog, for whatever reason, is rendered behind it.  (So if there is a problem, it's with the other mod.)

**Pull request merged**
